version: '3'
services:
  mosca:
    build: .
    image: mosca:dev
    environment:
      ID: mosca_1
      REDIS: redis
    depends_on:
      - redis
    ports:
      - 1883:1883
      - 80:80
    volumes:
      - ./config:/usr/src/app/config
  redis:
    image: redis:alpine
